# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sekeni_development

test:
  adapter: async
  channel_prefix: sekeni_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sekeni_production
  pool_size: 5
  redis:
    db: 0
    password: <%= ENV["REDIS_PASSWORD"] %>
